# Longitudional Impact of Intervention on Differential Abundance

## OGUs Common between GLMMs and differential abundance changes over time

```{r setup}
#| echo: false
#| eval: true
#| label: setup
#| cache: false

# This initial code block loads custom utility functions and environment variables
# These are stored in separate files to keep the main analysis clean and organized
suppressWarnings(suppressMessages({
  source("utils/r-utils.r")

  source("_environment.required")
  load("data/seqdata.RData")

  library(promicrobialTools)

  prefix <- "EvsBarm-"

  filepath <- get_results_dir(directory_naming = "both")
}))
```

Results will be saved to ``r filepath``.

## Comparision of ANCOM-BC Differentially Abundant OGUs and ZI-GLMM model results

```{r}
#| eval: true
#| label: FC2 + GLMM result comparisons

EvsBarm_ZI <- read.csv(
  file.path(
    RESULTS,
    "06a-zero-inflated-OGU-models/EvsBarm-OGU-zero-inflated-models",
    "EvsBarm-zero-inflated-ogu-fitted-model-significant-pvalues.csv"
  ),
  header = TRUE
)

EvsBarm_ANCOM <- read.csv(
  file.path(
    RESULTS,
    "07-differential-abundance-analysis/EvsBarm-ANCOM-BC/EvsBarm-DA-ancombc.csv"
  ),
  header = TRUE
)
```

```{r}
#| eval: true
#| label: FC2
#| fig-cap: NA
#| tbl-cap: NA

EvsBarm_ANCOM <- EvsBarm_ANCOM %>%
  mutate(FC = exp(abs(EvsBarm_ANCOM$`lfc_timepointEndpoint.armFeZnPM`))) %>%
  filter(
    `passed_ss_timepointEndpoint.armFeZnPM` == TRUE,
    `q_timepointEndpoint.armFeZnPM` <= 0.05
  ) %>%
  select(
    taxon,
    `lfc_timepointEndpoint.armFeZnPM`,
    FC,
    `p_timepointEndpoint.armFeZnPM`,
    `q_timepointEndpoint.armFeZnPM`,
    Result_FC1.2,
    Result_FC2
  )

kable(
  common <- EvsBarm_ZI %>%
    inner_join(., EvsBarm_ANCOM, by = c("outcome_id" = "taxon"))
)
```

There are no common OGUs

## Results Summary

```{r}
#| eval: true
#| echo: false
#| results: asis

list_all_results()
```

```{r}
#| eval: true
#| echo: false
#| results: asis
generate_results_section(directory_naming = "both")
```

## Appendix

```{r}
#| eval: true
#| echo: false
#| label: info

print(sessionInfo(), locale = FALSE)
```
